import os
import sys
import subprocess
import argparse

def main():
    parser = argparse.ArgumentParser(description="Full Covert Channel Decoder (GAN + BCH + AES)")
    parser.add_argument("server_log", help="The raw timing log generated by server.c")
    parser.add_argument("--threshold", type=float, default=0.20, help="GAP_THRESHOLD (Drop covers below this)")
    parser.add_argument("--decode", type=float, default=0.625, help="DECODE_THRESHOLD (Bit 0 vs Bit 1 midpoint)")
    args = parser.parse_args()

    if not os.path.exists(args.server_log):
        print(f"Error: {args.server_log} not found.")
        sys.exit(1)

    # 1. Compile C decoder if missing
    if not os.path.exists("./bch_decode"):
        print("[*] Compiling bch_decode.c...")
        subprocess.run(["gcc", "-o", "bch_decode", "bch_decode.c", "-lcrypto"], check=True)

    # 2. Extract Payloads from Server Log
    print(f"[*] Reading raw IPDs from {args.server_log}...")
    with open(args.server_log, 'r') as f:
        lines = f.readlines()

    payload_ipds = []
    total_ipds = 0
    for line in lines:
        line = line.strip()
        if not line: continue
        try:
            val = float(line)
            total_ipds += 1
            # Throw away the cover traffic (background noise)
            if val >= args.threshold:
                payload_ipds.append(val)
        except ValueError:
            pass

    print(f"[*] Processed {total_ipds} raw IPDs. Extracted {len(payload_ipds)} Payload Gaps.")

    if len(payload_ipds) == 0:
        print("[!] No payloads found above threshold. Exiting.")
        sys.exit(1)

    # 3. Save to a temporary file for bch_decode
    temp_file = "extracted_payloads.txt"
    with open(temp_file, 'w') as f:
        for ipd in payload_ipds:
            f.write(f"{ipd}\n")
    print(f"[*] Saved payloads to {temp_file}")

    # 4. Run the BCH Decoder
    print(f"\n[*] Running BCH Decoder & AES Decryption...")
    print("-" * 50)
    # Usage: ./bch_decode <m> <length> <t> <timing_file> <threshold>
    result = subprocess.run(["./bch_decode", "8", "255", "8", temp_file, str(args.decode)], capture_output=True)
    
    # Save the raw bytes to a file, removing trailing null padding
    output_file = "decoded_message.txt"
    cleaned_bytes = result.stdout.rstrip(b'\x00')
    
    with open(output_file, 'wb') as f:
        f.write(cleaned_bytes)
        
    print(result.stderr.decode('utf-8'))
    print("-" * 50)
    print(f"\n✅ Decoding Complete. The reconstructed file was saved to '{output_file}'!")

if __name__ == "__main__":
    main()
